language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - ~/.platformio

env:
    - PLATFORMIO_CI_SRC=examples/AirQualitySensor
    - PLATFORMIO_CI_SRC=examples/BatteryPoweredSensor
    - PLATFORMIO_CI_SRC=examples/BinarySwitchSleepSensor
    - PLATFORMIO_CI_SRC=examples/ClearEepromConfig
    - PLATFORMIO_CI_SRC=examples/CO2Sensor
    - PLATFORMIO_CI_SRC=examples/DimmableLEDActuator
    - PLATFORMIO_CI_SRC=examples/DimmableLight
    - PLATFORMIO_CI_SRC=examples/DustSensor
    - PLATFORMIO_CI_SRC=examples/DustSensorDSM
    - PLATFORMIO_CI_SRC=examples/EnergyMeterPulseSensor
    - PLATFORMIO_CI_SRC=examples/GatewayESP8266 PLATFORMIO_CI_BOARDS_ARGS="--board esp01 --board nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/GatewayESP8266MQTTClient PLATFORMIO_CI_BOARDS_ARGS="--board esp01 --board nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/GatewayESP8266OTA PLATFORMIO_CI_BOARDS_ARGS="--board esp01 --board nodemcuv2"
    - PLATFORMIO_CI_SRC=examples/GatewaySerial
    - PLATFORMIO_CI_SRC=examples/GatewaySerialRS485
    - PLATFORMIO_CI_SRC=examples/GatewayW5100
    - PLATFORMIO_CI_SRC=examples/GatewayW5100MQTTClient
    - PLATFORMIO_CI_SRC=examples/LightSensor
    - PLATFORMIO_CI_SRC=examples/MockMySensors
    - PLATFORMIO_CI_SRC=examples/MotionSensor
    - PLATFORMIO_CI_SRC=examples/MotionSensorRS485
    - PLATFORMIO_CI_SRC=examples/PHSensor
    - PLATFORMIO_CI_SRC=examples/PingPongSensor
    - PLATFORMIO_CI_SRC=examples/RelayActuator
    - PLATFORMIO_CI_SRC=examples/RepeaterNode
    - PLATFORMIO_CI_SRC=examples/SecretKnockSensor
    - PLATFORMIO_CI_SRC=examples/SecureActuator
    - PLATFORMIO_CI_SRC=examples/SecurityPersonalizer
    - PLATFORMIO_CI_SRC=examples/SoilMoistSensor
    - PLATFORMIO_CI_SRC=examples/UVSensor
    - PLATFORMIO_CI_SRC=examples/VibrationSensor
    - PLATFORMIO_CI_SRC=examples/WaterMeterPulseSensor

install:
    # Don't forget to switch to stable PlatformIO 3.0 (line below) when it will be released
    - pip install -U https://github.com/platformio/platformio/archive/develop.zip
    # - pip install -U platformio

    # update cached development platforms, packages and libraries
    - platformio update

    # install required libraries
    #- platformio lib --global install DigitalIO

script:
    - if [[ $PLATFORMIO_CI_BOARDS_ARGS ]]; then bash -c 'platformio ci --lib="." $PLATFORMIO_CI_BOARDS_ARGS'; else platformio ci  --lib="." --board uno --board megaatmega2560 --board esp01 --board nodemcuv2 --board zero; fi
